export const FEATURE_AUTH_KEY = "FEATURE_AUTH_KEY";

export const FEATURE_BOOKING_KEY = "FEATURE_BOOKING_KEY";

export const FEATURE_PATIENT_STORE_KEY = "FEATURE_PATIENT_STORE_KEY";

export const FEATURE_STAFF_KEY = "FEATURE_STAFF_KEY";

export const AUTH_SESSION_SWR_KEY = "AUTH_SESSION_SWR_KEY";

export const BOOKING_STORE_KEY = "BOOKING_STORE_KEY";

export const APPOINTMENT_SWR_KEY = "APPOINTMENT_SWR_KEY";
