export const AUTH_SESSION_SWR_KEY = "AUTH_SESSION_SWR_KEY";

export const BOOKING_STORE_KEY = "BOOKING_STORE_KEY";

export const APPOINTMENT_SWR_KEY = "APPOINTMENT_SWR_KEY";

export const AUTH_ERROR_SWR_KEY = "AUTH_ERROR_SWR_KEY";

export const AUTH_CONFIRM_LOGOUT_SWR_KEY = "AUTH_CONFIRM_LOGOUT_SWR_KEY";

export const DOCTOR_APPOINTMENTS_SWR_KEY = "DOCTOR_APPOINTMENTS_SWR_KEY";

export const STAFF_APPOINTMENTS_SWR_KEY = "STAFF_APPOINTMENTS_SWR_KEY";

export const FORCE_APPOINTMENT_SWR_KEY = "FORCE_APPOINTMENT_SWR_KEY";
