import { EXCEPTION_TYPE, GENDER, ROLE_NAME, SPECIALTY_TYPE, USER_STATUS } from "@/common";
import type { DoctorProfileResponse, DoctorScheduleExceptionResponse } from "@/interface/response";

export const MOCK_CURRENT_DOCTOR_PROFILE_ID = "doctor-profile-001";

const mockDoctorProfile: DoctorProfileResponse = {
  id: MOCK_CURRENT_DOCTOR_PROFILE_ID,
  doctorCode: "DOC-001",
  degree: "MD",
  experienceYears: 12,
  education: "University of Medicine and Pharmacy",
  bio: "Internal medicine physician with outpatient clinic experience.",
  consultationFee: 450000,
  averageRating: 4.8,
  totalReviews: 128,
  totalPatients: 2400,
  isFeatured: true,
  deleted: false,
  specialty: {
    id: "specialty-cardio",
    name: "Cardiology",
    slug: "cardiology",
    description: "Heart and vascular care",
    image: "/specialties/cardiology.jpg",
    displayOrder: 1,
    specialtyType: SPECIALTY_TYPE.CARDIOLOGY,
    isActive: true,
  },
  user: {
    id: "user-doctor-001",
    email: "doctor.nguyen@example.com",
    fullName: "Dr. Nguyen Minh Anh",
    phone: "0901000001",
    role: ROLE_NAME.DOCTOR,
    gender: GENDER.FEMALE,
    dateOfBirth: "1984-03-12",
    status: USER_STATUS.ACTIVE,
    pathAvatar: "",
    emailVerified: true,
    phoneVerified: true,
  },
};

const otherDoctorProfile: DoctorProfileResponse = {
  ...mockDoctorProfile,
  id: "doctor-profile-002",
  doctorCode: "DOC-002",
  user: {
    ...mockDoctorProfile.user,
    id: "user-doctor-002",
    email: "doctor.tran@example.com",
    fullName: "Dr. Tran Quoc Bao",
  },
};

export const MOCK_DOCTOR_SCHEDULE_EXCEPTIONS: DoctorScheduleExceptionResponse[] = [
  {
    id: "exception-001",
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: null,
    deletedAt: null,
    doctorProfile: mockDoctorProfile,
    exceptionDate: "2026-06-10",
    type: EXCEPTION_TYPE.LEAVE,
    reason: "Annual leave",
  },
  {
    id: "exception-002",
    createdAt: "2026-06-02T08:00:00Z",
    updatedAt: null,
    deletedAt: null,
    doctorProfile: mockDoctorProfile,
    exceptionDate: "2026-06-13",
    type: EXCEPTION_TYPE.EXTRA,
    reason: "Volunteering weekend clinic",
  },
  {
    id: "exception-003",
    createdAt: "2026-06-03T08:00:00Z",
    updatedAt: null,
    deletedAt: null,
    doctorProfile: mockDoctorProfile,
    exceptionDate: "2026-06-22",
    type: EXCEPTION_TYPE.LEAVE,
    reason: "Conference attendance",
  },
  {
    id: "exception-004",
    createdAt: "2026-06-04T08:00:00Z",
    updatedAt: null,
    deletedAt: null,
    doctorProfile: mockDoctorProfile,
    exceptionDate: "2026-06-28",
    type: EXCEPTION_TYPE.EXTRA,
    reason: "Additional patient follow-up sessions",
  },
  {
    id: "exception-005",
    createdAt: "2026-06-05T08:00:00Z",
    updatedAt: null,
    deletedAt: null,
    doctorProfile: mockDoctorProfile,
    exceptionDate: "2026-07-03",
    type: EXCEPTION_TYPE.LEAVE,
    reason: "Family emergency",
  },
  {
    id: "exception-006",
    createdAt: "2026-06-06T08:00:00Z",
    updatedAt: null,
    deletedAt: null,
    doctorProfile: mockDoctorProfile,
    exceptionDate: "2026-07-12",
    type: EXCEPTION_TYPE.EXTRA,
    reason: "Weekend vaccination support",
  },
  {
    id: "exception-007",
    createdAt: "2026-06-07T08:00:00Z",
    updatedAt: null,
    deletedAt: null,
    doctorProfile: otherDoctorProfile,
    exceptionDate: "2026-06-16",
    type: EXCEPTION_TYPE.LEAVE,
    reason: "Medical seminar",
  },
];
