"use client";

import type { DoctorProfileResponse } from "@/interface/response";
import { SPECIALTY_TYPE } from "@/common";

export const mockDoctors: DoctorProfileResponse[] = [
  {
    id: "1",
    user: {
      id: "u1",
      email: "nguyen.van.minh@example.com",
      fullName: "TS. BS Nguyễn Văn Minh",
      phone: "0901234567",
      role: "DOCTOR",
      gender: "MALE",
      dateOfBirth: "1975-03-15",
      status: "ACTIVE",
      pathAvatar: "",
      emailVerified: true,
      phoneVerified: true,
      createdAt: "2024-01-01T00:00:00",
      updatedAt: null,
      deletedAt: null,
      deleted: false,
    },
    doctorCode: "BS-001",
    specialty: {
      id: "1",
      name: "Cardiology",
      slug: "cardiology",
      description: "Heart and cardiovascular system",
      image: "",
      displayOrder: 1,
      specialtyType: SPECIALTY_TYPE.CARDIOLOGY,
      isActive: true,
    },
    degree: "Tiến sĩ",
    experienceYears: 18,
    education: "Đại học Y Hà Nội",
    bio: "Chuyên gia tim mạch với 18 năm kinh nghiệm",
    consultationFee: 500000,
    averageRating: 4.9,
    totalReviews: 256,
    totalPatients: 3500,
    isFeatured: true,
    createdAt: "2024-01-01T00:00:00",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "2",
    user: {
      id: "u2",
      email: "tran.thi.huong@example.com",
      fullName: "ThS. BS Trần Thị Hương",
      phone: "0907654321",
      role: "DOCTOR",
      gender: "FEMALE",
      dateOfBirth: "1982-07-22",
      status: "ACTIVE",
      pathAvatar: "",
      emailVerified: true,
      phoneVerified: true,
      createdAt: "2024-02-15T00:00:00",
      updatedAt: null,
      deletedAt: null,
      deleted: false,
    },
    doctorCode: "BS-002",
    specialty: {
      id: "3",
      name: "Pediatrics",
      slug: "pediatrics",
      description: "Children's health care",
      image: "",
      displayOrder: 3,
      specialtyType: SPECIALTY_TYPE.PEDIATRICS,
      isActive: true,
    },
    degree: "Thạc sĩ",
    experienceYears: 12,
    education: "Đại học Y Hà Nội",
    bio: "Bác sĩ nhi khoa tận tâm với trẻ em",
    consultationFee: 350000,
    averageRating: 4.8,
    totalReviews: 189,
    totalPatients: 2800,
    isFeatured: false,
    createdAt: "2024-02-15T00:00:00",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "3",
    user: {
      id: "u3",
      email: "le.van.cuong@example.com",
      fullName: "BS Lê Văn Cường",
      phone: "0912345678",
      role: "DOCTOR",
      gender: "MALE",
      dateOfBirth: "1985-11-08",
      status: "ACTIVE",
      pathAvatar: "",
      emailVerified: true,
      phoneVerified: false,
      createdAt: "2024-03-01T00:00:00",
      updatedAt: null,
      deletedAt: null,
      deleted: false,
    },
    doctorCode: "BS-003",
    specialty: {
      id: "2",
      name: "Neurology",
      slug: "neurology",
      description: "Nervous system disorders",
      image: "",
      displayOrder: 2,
      specialtyType: SPECIALTY_TYPE.NEUROLOGY,
      isActive: true,
    },
    degree: "Bác sĩ",
    experienceYears: 8,
    education: "Đại học Y Hà Nội",
    bio: "Bác sĩ thần kinh học chuyên điều trị",
    consultationFee: 400000,
    averageRating: 4.6,
    totalReviews: 120,
    totalPatients: 1500,
    isFeatured: false,
    createdAt: "2024-03-01T00:00:00",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "4",
    user: {
      id: "u4",
      email: "pham.thi.lan@example.com",
      fullName: "BS Phạm Thị Lan",
      phone: "0987654321",
      role: "DOCTOR",
      gender: "FEMALE",
      dateOfBirth: "1990-05-20",
      status: "INACTIVE",
      pathAvatar: "",
      emailVerified: false,
      phoneVerified: true,
      createdAt: "2024-04-10T00:00:00",
      updatedAt: null,
      deletedAt: null,
      deleted: false,
    },
    doctorCode: "BS-004",
    specialty: {
      id: "4",
      name: "Dermatology",
      slug: "dermatology",
      description: "Skin conditions and treatments",
      image: "",
      displayOrder: 4,
      specialtyType: SPECIALTY_TYPE.DERMATOLOGY,
      isActive: true,
    },
    degree: "Bác sĩ",
    experienceYears: 5,
    education: "Đại học Y Hà Nội",
    bio: "Bác sĩ da liễu chuyên điều trị mụn và nám",
    consultationFee: 300000,
    averageRating: 4.5,
    totalReviews: 85,
    totalPatients: 900,
    isFeatured: false,
    createdAt: "2024-04-10T00:00:00",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
];
