"use client";

import type { ServiceResponse } from "@/interface/response";

export const mockServices: ServiceResponse[] = [
  {
    id: "1",
    name: "General Health Checkup",
    slug: "general-health-checkup",
    description: "Comprehensive health examination and screening",
    price: 500000,
    promotionalPrice: 450000,
    duration: 60,
    image: "",
    isFeatured: true,
    isActive: true,
    createdAt: "2025-01-15T08:00:00",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "2",
    name: "Cardiac Consultation",
    slug: "cardiac-consultation",
    description: "Expert cardiac assessment and heart health evaluation",
    price: 800000,
    promotionalPrice: 0,
    duration: 45,
    image: "",
    isFeatured: true,
    isActive: true,
    createdAt: "2025-01-20T10:00:00",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "3",
    name: "Neurological Examination",
    slug: "neurological-examination",
    description: "Thorough assessment of nervous system function",
    price: 700000,
    promotionalPrice: 650000,
    duration: 45,
    image: "",
    isFeatured: false,
    isActive: true,
    createdAt: "2025-02-01T09:00:00",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "4",
    name: "Pediatric Vaccination",
    slug: "pediatric-vaccination",
    description: "Standard vaccination schedule for children",
    price: 300000,
    promotionalPrice: 0,
    duration: 20,
    image: "",
    isFeatured: false,
    isActive: true,
    createdAt: "2025-02-10T08:30:00",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "5",
    name: "Skin Allergy Test",
    slug: "skin-allergy-test",
    description: "Comprehensive skin allergy screening and testing",
    price: 600000,
    promotionalPrice: 550000,
    duration: 30,
    image: "",
    isFeatured: false,
    isActive: false,
    createdAt: "2025-03-01T14:00:00",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
];
