export enum ROLE_NAME {
  ADMIN = "ADMIN",
  DOCTOR = "DOCTOR",
  PATIENT = "PATIENT",
  STAFF = "STAFF",
  GUEST = "GUEST",
}

export enum GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
}

export enum USER_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  BANNED = "BANNED",
}

export enum SPECIALTY_TYPE {
  GENERAL = "GENERAL",
  SURGERY = "SURGERY",
  PEDIATRICS = "PEDIATRICS",
  DERMATOLOGY = "DERMATOLOGY",
  CARDIOLOGY = "CARDIOLOGY",
  ORTHOPEDICS = "ORTHOPEDICS",
  NEUROLOGY = "NEUROLOGY",
  PSYCHIATRY = "PSYCHIATRY",
  GYNECOLOGY = "GYNECOLOGY",
  ENDOCRINOLOGY = "ENDOCRINOLOGY",
}

export enum BLOOD_TYPE {
  A_POSITIVE = "A+",
  A_NEGATIVE = "A-",
  B_POSITIVE = "B+",
  B_NEGATIVE = "B-",
  AB_POSITIVE = "AB+",
  AB_NEGATIVE = "AB-",
  O_POSITIVE = "O+",
  O_NEGATIVE = "O-",
}

export enum APPOINTMENT_STATUS {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CHECKED_IN = "CHECKED_IN",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  NO_SHOW = "NO_SHOW",
}

export enum BOOKING_TYPE {
  ONLINE = "ONLINE",
  PHONE = "PHONE",
  WALK_IN = "WALK_IN",
}

export enum REVIEW_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum EXCEPTION_TYPE {
  LEAVE = "LEAVE", // nghỉ phép (T2-T6)
  EXTRA = "EXTRA", // làm thêm (T7, CN)
}

export enum ITEM_TYPE {
  SERVICE = "SERVICE",
  MEDICATION = "MEDICATION",
  LAB_TEST = "LAB_TEST",
  OTHER = "OTHER",
}

export enum INVOICE_STATUS {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
}
