export enum ROLE_NAME {
  ADMIN = "ADMIN",
  DOCTOR = "DOCTOR",
  PATIENT = "PATIENT",
  STAFF = "STAFF",
  GUEST = "GUEST",
}

export enum GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
}

export enum USER_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  BANNED = "BANNED",
}

export enum SPECIALTY_TYPE {
  GENERAL = "GENERAL",
  SURGERY = "SURGERY",
  PEDIATRICS = "PEDIATRICS",
  DERMATOLOGY = "DERMATOLOGY",
  CARDIOLOGY = "CARDIOLOGY",
  ORTHOPEDICS = "ORTHOPEDICS",
  NEUROLOGY = "NEUROLOGY",
  PSYCHIATRY = "PSYCHIATRY",
  GYNECOLOGY = "GYNECOLOGY",
  ENDOCRINOLOGY = "ENDOCRINOLOGY",
}
